package test.dao;

import java.util.List;
import test.model.Cars;

public interface CarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    int insert(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    Cars selectByPrimaryKey(String carsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    List<Cars> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cars record);
}