package test.dao;

import java.util.List;
import test.model.Dispoint;

public interface DispointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispoint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dispointid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispoint
     *
     * @mbg.generated
     */
    int insert(Dispoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispoint
     *
     * @mbg.generated
     */
    Dispoint selectByPrimaryKey(Integer dispointid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispoint
     *
     * @mbg.generated
     */
    List<Dispoint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dispoint record);
}