package test.dao;

import java.util.List;
import test.model.Handover;

public interface HandoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String startcity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    int insert(Handover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    Handover selectByPrimaryKey(String startcity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    List<Handover> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Handover record);
}