package test.dao;

import java.util.List;
import test.model.Usergroup;

public interface UsergroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String usergroupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroup
     *
     * @mbg.generated
     */
    int insert(Usergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroup
     *
     * @mbg.generated
     */
    Usergroup selectByPrimaryKey(String usergroupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroup
     *
     * @mbg.generated
     */
    List<Usergroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usergroup record);
}