package test.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbg.generated
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.usergroupId
     *
     * @mbg.generated
     */
    private Integer usergroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminstatus
     *
     * @mbg.generated
     */
    private Integer adminstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admincity
     *
     * @mbg.generated
     */
    private String admincity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminaddress
     *
     * @mbg.generated
     */
    private String adminaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbg.generated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbg.generated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.name
     *
     * @return the value of admin.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.name
     *
     * @param name the value for admin.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.usergroupId
     *
     * @return the value of admin.usergroupId
     *
     * @mbg.generated
     */
    public Integer getUsergroupid() {
        return usergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.usergroupId
     *
     * @param usergroupid the value for admin.usergroupId
     *
     * @mbg.generated
     */
    public void setUsergroupid(Integer usergroupid) {
        this.usergroupid = usergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminstatus
     *
     * @return the value of admin.adminstatus
     *
     * @mbg.generated
     */
    public Integer getAdminstatus() {
        return adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminstatus
     *
     * @param adminstatus the value for admin.adminstatus
     *
     * @mbg.generated
     */
    public void setAdminstatus(Integer adminstatus) {
        this.adminstatus = adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admincity
     *
     * @return the value of admin.admincity
     *
     * @mbg.generated
     */
    public String getAdmincity() {
        return admincity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admincity
     *
     * @param admincity the value for admin.admincity
     *
     * @mbg.generated
     */
    public void setAdmincity(String admincity) {
        this.admincity = admincity == null ? null : admincity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminaddress
     *
     * @return the value of admin.adminaddress
     *
     * @mbg.generated
     */
    public String getAdminaddress() {
        return adminaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminaddress
     *
     * @param adminaddress the value for admin.adminaddress
     *
     * @mbg.generated
     */
    public void setAdminaddress(String adminaddress) {
        this.adminaddress = adminaddress == null ? null : adminaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.remarks
     *
     * @return the value of admin.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.remarks
     *
     * @param remarks the value for admin.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}