package test.model;

import java.util.Date;

public class Cars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carsId
     *
     * @mbg.generated
     */
    private String carsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carsmodel
     *
     * @mbg.generated
     */
    private String carsmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.candi
     *
     * @mbg.generated
     */
    private String candi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.routeId
     *
     * @mbg.generated
     */
    private String routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.dom
     *
     * @mbg.generated
     */
    private Date dom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.dop
     *
     * @mbg.generated
     */
    private Date dop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carsId
     *
     * @return the value of cars.carsId
     *
     * @mbg.generated
     */
    public String getCarsid() {
        return carsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carsId
     *
     * @param carsid the value for cars.carsId
     *
     * @mbg.generated
     */
    public void setCarsid(String carsid) {
        this.carsid = carsid == null ? null : carsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carsmodel
     *
     * @return the value of cars.carsmodel
     *
     * @mbg.generated
     */
    public String getCarsmodel() {
        return carsmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carsmodel
     *
     * @param carsmodel the value for cars.carsmodel
     *
     * @mbg.generated
     */
    public void setCarsmodel(String carsmodel) {
        this.carsmodel = carsmodel == null ? null : carsmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.candi
     *
     * @return the value of cars.candi
     *
     * @mbg.generated
     */
    public String getCandi() {
        return candi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.candi
     *
     * @param candi the value for cars.candi
     *
     * @mbg.generated
     */
    public void setCandi(String candi) {
        this.candi = candi == null ? null : candi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.routeId
     *
     * @return the value of cars.routeId
     *
     * @mbg.generated
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.routeId
     *
     * @param routeid the value for cars.routeId
     *
     * @mbg.generated
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.dom
     *
     * @return the value of cars.dom
     *
     * @mbg.generated
     */
    public Date getDom() {
        return dom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.dom
     *
     * @param dom the value for cars.dom
     *
     * @mbg.generated
     */
    public void setDom(Date dom) {
        this.dom = dom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.dop
     *
     * @return the value of cars.dop
     *
     * @mbg.generated
     */
    public Date getDop() {
        return dop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.dop
     *
     * @param dop the value for cars.dop
     *
     * @mbg.generated
     */
    public void setDop(Date dop) {
        this.dop = dop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.remarks
     *
     * @return the value of cars.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.remarks
     *
     * @param remarks the value for cars.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}