package test.model;

public class Cityarea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.cityareaId
     *
     * @mbg.generated
     */
    private String cityareaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.areaname
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.countryId
     *
     * @mbg.generated
     */
    private String countryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.cityareaId
     *
     * @return the value of cityarea.cityareaId
     *
     * @mbg.generated
     */
    public String getCityareaid() {
        return cityareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.cityareaId
     *
     * @param cityareaid the value for cityarea.cityareaId
     *
     * @mbg.generated
     */
    public void setCityareaid(String cityareaid) {
        this.cityareaid = cityareaid == null ? null : cityareaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.areaname
     *
     * @return the value of cityarea.areaname
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.areaname
     *
     * @param areaname the value for cityarea.areaname
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.countryId
     *
     * @return the value of cityarea.countryId
     *
     * @mbg.generated
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.countryId
     *
     * @param countryid the value for cityarea.countryId
     *
     * @mbg.generated
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid == null ? null : countryid.trim();
    }
}