package test.model;

import java.util.Date;

public class Consumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumerId
     *
     * @mbg.generated
     */
    private String consumerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.usergroupId
     *
     * @mbg.generated
     */
    private String usergroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.conpassword
     *
     * @mbg.generated
     */
    private String conpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.adaress
     *
     * @mbg.generated
     */
    private String adaress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumerId
     *
     * @return the value of consumer.consumerId
     *
     * @mbg.generated
     */
    public String getConsumerid() {
        return consumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumerId
     *
     * @param consumerid the value for consumer.consumerId
     *
     * @mbg.generated
     */
    public void setConsumerid(String consumerid) {
        this.consumerid = consumerid == null ? null : consumerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.name
     *
     * @return the value of consumer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.name
     *
     * @param name the value for consumer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.sex
     *
     * @return the value of consumer.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.sex
     *
     * @param sex the value for consumer.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.usergroupId
     *
     * @return the value of consumer.usergroupId
     *
     * @mbg.generated
     */
    public String getUsergroupid() {
        return usergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.usergroupId
     *
     * @param usergroupid the value for consumer.usergroupId
     *
     * @mbg.generated
     */
    public void setUsergroupid(String usergroupid) {
        this.usergroupid = usergroupid == null ? null : usergroupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.conpassword
     *
     * @return the value of consumer.conpassword
     *
     * @mbg.generated
     */
    public String getConpassword() {
        return conpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.conpassword
     *
     * @param conpassword the value for consumer.conpassword
     *
     * @mbg.generated
     */
    public void setConpassword(String conpassword) {
        this.conpassword = conpassword == null ? null : conpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.phone
     *
     * @return the value of consumer.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.phone
     *
     * @param phone the value for consumer.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.birthday
     *
     * @return the value of consumer.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.birthday
     *
     * @param birthday the value for consumer.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.adaress
     *
     * @return the value of consumer.adaress
     *
     * @mbg.generated
     */
    public String getAdaress() {
        return adaress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.adaress
     *
     * @param adaress the value for consumer.adaress
     *
     * @mbg.generated
     */
    public void setAdaress(String adaress) {
        this.adaress = adaress == null ? null : adaress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.remarks
     *
     * @return the value of consumer.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.remarks
     *
     * @param remarks the value for consumer.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}