package test.model;

public class Dispoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.dispointId
     *
     * @mbg.generated
     */
    private Integer dispointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.dispointname
     *
     * @mbg.generated
     */
    private String dispointname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.provinceId
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.countryId
     *
     * @mbg.generated
     */
    private String countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.adminId
     *
     * @mbg.generated
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispoint.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.dispointId
     *
     * @return the value of dispoint.dispointId
     *
     * @mbg.generated
     */
    public Integer getDispointid() {
        return dispointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.dispointId
     *
     * @param dispointid the value for dispoint.dispointId
     *
     * @mbg.generated
     */
    public void setDispointid(Integer dispointid) {
        this.dispointid = dispointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.dispointname
     *
     * @return the value of dispoint.dispointname
     *
     * @mbg.generated
     */
    public String getDispointname() {
        return dispointname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.dispointname
     *
     * @param dispointname the value for dispoint.dispointname
     *
     * @mbg.generated
     */
    public void setDispointname(String dispointname) {
        this.dispointname = dispointname == null ? null : dispointname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.provinceId
     *
     * @return the value of dispoint.provinceId
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.provinceId
     *
     * @param provinceid the value for dispoint.provinceId
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.countryId
     *
     * @return the value of dispoint.countryId
     *
     * @mbg.generated
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.countryId
     *
     * @param countryid the value for dispoint.countryId
     *
     * @mbg.generated
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid == null ? null : countryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.adminId
     *
     * @return the value of dispoint.adminId
     *
     * @mbg.generated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.adminId
     *
     * @param adminid the value for dispoint.adminId
     *
     * @mbg.generated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.phone
     *
     * @return the value of dispoint.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.phone
     *
     * @param phone the value for dispoint.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.address
     *
     * @return the value of dispoint.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.address
     *
     * @param address the value for dispoint.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispoint.remarks
     *
     * @return the value of dispoint.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispoint.remarks
     *
     * @param remarks the value for dispoint.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}