package test.model;

public class Disscope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscope.disscopeId
     *
     * @mbg.generated
     */
    private Integer disscopeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscope.disscopename
     *
     * @mbg.generated
     */
    private String disscopename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscope.disprice
     *
     * @mbg.generated
     */
    private Long disprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscope.countryId
     *
     * @mbg.generated
     */
    private String countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disscope.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscope.disscopeId
     *
     * @return the value of disscope.disscopeId
     *
     * @mbg.generated
     */
    public Integer getDisscopeid() {
        return disscopeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscope.disscopeId
     *
     * @param disscopeid the value for disscope.disscopeId
     *
     * @mbg.generated
     */
    public void setDisscopeid(Integer disscopeid) {
        this.disscopeid = disscopeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscope.disscopename
     *
     * @return the value of disscope.disscopename
     *
     * @mbg.generated
     */
    public String getDisscopename() {
        return disscopename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscope.disscopename
     *
     * @param disscopename the value for disscope.disscopename
     *
     * @mbg.generated
     */
    public void setDisscopename(String disscopename) {
        this.disscopename = disscopename == null ? null : disscopename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscope.disprice
     *
     * @return the value of disscope.disprice
     *
     * @mbg.generated
     */
    public Long getDisprice() {
        return disprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscope.disprice
     *
     * @param disprice the value for disscope.disprice
     *
     * @mbg.generated
     */
    public void setDisprice(Long disprice) {
        this.disprice = disprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscope.countryId
     *
     * @return the value of disscope.countryId
     *
     * @mbg.generated
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscope.countryId
     *
     * @param countryid the value for disscope.countryId
     *
     * @mbg.generated
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid == null ? null : countryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disscope.remarks
     *
     * @return the value of disscope.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disscope.remarks
     *
     * @param remarks the value for disscope.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}