package test.model;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordersId
     *
     * @mbg.generated
     */
    private String ordersid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderstype
     *
     * @mbg.generated
     */
    private Integer orderstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.handoverId
     *
     * @mbg.generated
     */
    private String handoverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsname
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodswieght
     *
     * @mbg.generated
     */
    private Integer goodswieght;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.mailer
     *
     * @mbg.generated
     */
    private String mailer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.mailaddress
     *
     * @mbg.generated
     */
    private String mailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.readdress
     *
     * @mbg.generated
     */
    private String readdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderstatus
     *
     * @mbg.generated
     */
    private Integer orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.mailphone
     *
     * @mbg.generated
     */
    private String mailphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.consigneephone
     *
     * @mbg.generated
     */
    private String consigneephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.startcity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.middlecity
     *
     * @mbg.generated
     */
    private String middlecity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.finalcity
     *
     * @mbg.generated
     */
    private String finalcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.yunsongprice
     *
     * @mbg.generated
     */
    private Long yunsongprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.disprice
     *
     * @mbg.generated
     */
    private Long disprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.yunshuprice
     *
     * @mbg.generated
     */
    private Long yunshuprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.finalprice
     *
     * @mbg.generated
     */
    private String finalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.car
     *
     * @mbg.generated
     */
    private String car;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordersId
     *
     * @return the value of orders.ordersId
     *
     * @mbg.generated
     */
    public String getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordersId
     *
     * @param ordersid the value for orders.ordersId
     *
     * @mbg.generated
     */
    public void setOrdersid(String ordersid) {
        this.ordersid = ordersid == null ? null : ordersid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderstype
     *
     * @return the value of orders.orderstype
     *
     * @mbg.generated
     */
    public Integer getOrderstype() {
        return orderstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderstype
     *
     * @param orderstype the value for orders.orderstype
     *
     * @mbg.generated
     */
    public void setOrderstype(Integer orderstype) {
        this.orderstype = orderstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.handoverId
     *
     * @return the value of orders.handoverId
     *
     * @mbg.generated
     */
    public String getHandoverid() {
        return handoverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.handoverId
     *
     * @param handoverid the value for orders.handoverId
     *
     * @mbg.generated
     */
    public void setHandoverid(String handoverid) {
        this.handoverid = handoverid == null ? null : handoverid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsname
     *
     * @return the value of orders.goodsname
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsname
     *
     * @param goodsname the value for orders.goodsname
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodswieght
     *
     * @return the value of orders.goodswieght
     *
     * @mbg.generated
     */
    public Integer getGoodswieght() {
        return goodswieght;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodswieght
     *
     * @param goodswieght the value for orders.goodswieght
     *
     * @mbg.generated
     */
    public void setGoodswieght(Integer goodswieght) {
        this.goodswieght = goodswieght;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.mailer
     *
     * @return the value of orders.mailer
     *
     * @mbg.generated
     */
    public String getMailer() {
        return mailer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.mailer
     *
     * @param mailer the value for orders.mailer
     *
     * @mbg.generated
     */
    public void setMailer(String mailer) {
        this.mailer = mailer == null ? null : mailer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.mailaddress
     *
     * @return the value of orders.mailaddress
     *
     * @mbg.generated
     */
    public String getMailaddress() {
        return mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.mailaddress
     *
     * @param mailaddress the value for orders.mailaddress
     *
     * @mbg.generated
     */
    public void setMailaddress(String mailaddress) {
        this.mailaddress = mailaddress == null ? null : mailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.readdress
     *
     * @return the value of orders.readdress
     *
     * @mbg.generated
     */
    public String getReaddress() {
        return readdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.readdress
     *
     * @param readdress the value for orders.readdress
     *
     * @mbg.generated
     */
    public void setReaddress(String readdress) {
        this.readdress = readdress == null ? null : readdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderstatus
     *
     * @return the value of orders.orderstatus
     *
     * @mbg.generated
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderstatus
     *
     * @param orderstatus the value for orders.orderstatus
     *
     * @mbg.generated
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.mailphone
     *
     * @return the value of orders.mailphone
     *
     * @mbg.generated
     */
    public String getMailphone() {
        return mailphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.mailphone
     *
     * @param mailphone the value for orders.mailphone
     *
     * @mbg.generated
     */
    public void setMailphone(String mailphone) {
        this.mailphone = mailphone == null ? null : mailphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.consignee
     *
     * @return the value of orders.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.consignee
     *
     * @param consignee the value for orders.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.consigneephone
     *
     * @return the value of orders.consigneephone
     *
     * @mbg.generated
     */
    public String getConsigneephone() {
        return consigneephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.consigneephone
     *
     * @param consigneephone the value for orders.consigneephone
     *
     * @mbg.generated
     */
    public void setConsigneephone(String consigneephone) {
        this.consigneephone = consigneephone == null ? null : consigneephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.startcity
     *
     * @return the value of orders.startcity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.startcity
     *
     * @param startcity the value for orders.startcity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.middlecity
     *
     * @return the value of orders.middlecity
     *
     * @mbg.generated
     */
    public String getMiddlecity() {
        return middlecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.middlecity
     *
     * @param middlecity the value for orders.middlecity
     *
     * @mbg.generated
     */
    public void setMiddlecity(String middlecity) {
        this.middlecity = middlecity == null ? null : middlecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.finalcity
     *
     * @return the value of orders.finalcity
     *
     * @mbg.generated
     */
    public String getFinalcity() {
        return finalcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.finalcity
     *
     * @param finalcity the value for orders.finalcity
     *
     * @mbg.generated
     */
    public void setFinalcity(String finalcity) {
        this.finalcity = finalcity == null ? null : finalcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.yunsongprice
     *
     * @return the value of orders.yunsongprice
     *
     * @mbg.generated
     */
    public Long getYunsongprice() {
        return yunsongprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.yunsongprice
     *
     * @param yunsongprice the value for orders.yunsongprice
     *
     * @mbg.generated
     */
    public void setYunsongprice(Long yunsongprice) {
        this.yunsongprice = yunsongprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.disprice
     *
     * @return the value of orders.disprice
     *
     * @mbg.generated
     */
    public Long getDisprice() {
        return disprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.disprice
     *
     * @param disprice the value for orders.disprice
     *
     * @mbg.generated
     */
    public void setDisprice(Long disprice) {
        this.disprice = disprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.yunshuprice
     *
     * @return the value of orders.yunshuprice
     *
     * @mbg.generated
     */
    public Long getYunshuprice() {
        return yunshuprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.yunshuprice
     *
     * @param yunshuprice the value for orders.yunshuprice
     *
     * @mbg.generated
     */
    public void setYunshuprice(Long yunshuprice) {
        this.yunshuprice = yunshuprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.finalprice
     *
     * @return the value of orders.finalprice
     *
     * @mbg.generated
     */
    public String getFinalprice() {
        return finalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.finalprice
     *
     * @param finalprice the value for orders.finalprice
     *
     * @mbg.generated
     */
    public void setFinalprice(String finalprice) {
        this.finalprice = finalprice == null ? null : finalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.car
     *
     * @return the value of orders.car
     *
     * @mbg.generated
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.car
     *
     * @param car the value for orders.car
     *
     * @mbg.generated
     */
    public void setCar(String car) {
        this.car = car == null ? null : car.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.remarks
     *
     * @return the value of orders.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.remarks
     *
     * @param remarks the value for orders.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}