package test.model;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeId
     *
     * @mbg.generated
     */
    private String routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routename
     *
     * @mbg.generated
     */
    private String routename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startprovince
     *
     * @mbg.generated
     */
    private String startprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startcity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.middleprovince
     *
     * @mbg.generated
     */
    private String middleprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.middlecity
     *
     * @mbg.generated
     */
    private String middlecity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.finalprovince
     *
     * @mbg.generated
     */
    private String finalprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.finalcity
     *
     * @mbg.generated
     */
    private String finalcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.tranprice
     *
     * @mbg.generated
     */
    private Long tranprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeId
     *
     * @return the value of route.routeId
     *
     * @mbg.generated
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeId
     *
     * @param routeid the value for route.routeId
     *
     * @mbg.generated
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routename
     *
     * @return the value of route.routename
     *
     * @mbg.generated
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routename
     *
     * @param routename the value for route.routename
     *
     * @mbg.generated
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startprovince
     *
     * @return the value of route.startprovince
     *
     * @mbg.generated
     */
    public String getStartprovince() {
        return startprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startprovince
     *
     * @param startprovince the value for route.startprovince
     *
     * @mbg.generated
     */
    public void setStartprovince(String startprovince) {
        this.startprovince = startprovince == null ? null : startprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startcity
     *
     * @return the value of route.startcity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startcity
     *
     * @param startcity the value for route.startcity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.middleprovince
     *
     * @return the value of route.middleprovince
     *
     * @mbg.generated
     */
    public String getMiddleprovince() {
        return middleprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.middleprovince
     *
     * @param middleprovince the value for route.middleprovince
     *
     * @mbg.generated
     */
    public void setMiddleprovince(String middleprovince) {
        this.middleprovince = middleprovince == null ? null : middleprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.middlecity
     *
     * @return the value of route.middlecity
     *
     * @mbg.generated
     */
    public String getMiddlecity() {
        return middlecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.middlecity
     *
     * @param middlecity the value for route.middlecity
     *
     * @mbg.generated
     */
    public void setMiddlecity(String middlecity) {
        this.middlecity = middlecity == null ? null : middlecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.finalprovince
     *
     * @return the value of route.finalprovince
     *
     * @mbg.generated
     */
    public String getFinalprovince() {
        return finalprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.finalprovince
     *
     * @param finalprovince the value for route.finalprovince
     *
     * @mbg.generated
     */
    public void setFinalprovince(String finalprovince) {
        this.finalprovince = finalprovince == null ? null : finalprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.finalcity
     *
     * @return the value of route.finalcity
     *
     * @mbg.generated
     */
    public String getFinalcity() {
        return finalcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.finalcity
     *
     * @param finalcity the value for route.finalcity
     *
     * @mbg.generated
     */
    public void setFinalcity(String finalcity) {
        this.finalcity = finalcity == null ? null : finalcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.tranprice
     *
     * @return the value of route.tranprice
     *
     * @mbg.generated
     */
    public Long getTranprice() {
        return tranprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.tranprice
     *
     * @param tranprice the value for route.tranprice
     *
     * @mbg.generated
     */
    public void setTranprice(Long tranprice) {
        this.tranprice = tranprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.remarks
     *
     * @return the value of route.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.remarks
     *
     * @param remarks the value for route.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}