package test.model;

public class Usergroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.usergroupId
     *
     * @mbg.generated
     */
    private String usergroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.usergroupname
     *
     * @mbg.generated
     */
    private String usergroupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.usergroupId
     *
     * @return the value of usergroup.usergroupId
     *
     * @mbg.generated
     */
    public String getUsergroupid() {
        return usergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.usergroupId
     *
     * @param usergroupid the value for usergroup.usergroupId
     *
     * @mbg.generated
     */
    public void setUsergroupid(String usergroupid) {
        this.usergroupid = usergroupid == null ? null : usergroupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.usergroupname
     *
     * @return the value of usergroup.usergroupname
     *
     * @mbg.generated
     */
    public String getUsergroupname() {
        return usergroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.usergroupname
     *
     * @param usergroupname the value for usergroup.usergroupname
     *
     * @mbg.generated
     */
    public void setUsergroupname(String usergroupname) {
        this.usergroupname = usergroupname == null ? null : usergroupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.remarks
     *
     * @return the value of usergroup.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.remarks
     *
     * @param remarks the value for usergroup.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}